language: go
sudo: true

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_extended_0.73.0_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb # This provides the latest version of Hugo to Travis CI

script:
  - hugo 

deploy:
  local_dir: public
  repo: changelog-wiki/changelog-wiki.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: gh-pages # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: nickolas@gupton.xyz
  name: "Nickolas Gupton"
  on:
    branch: master